apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-management.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "user-management.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "user-management.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwtSecret.name }}
                  key: {{ .Values.jwtSecret.key }}
            - name: DB_HOST
              value: {{ include "user-management.fullname" . }}-postgres
