version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/user_management_db
      PORT: 3000

  postgres:
    image: postgres:latest
    container_name: user_management_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: