replicaCount: 3

image:
  repository: ghcr.io/mingleflix/usermanagement
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

imagePullSecrets:
  - name: ghcr-io-secret